# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 963e78abdd2ccd936a5319c5789d48639c4b282bb9dff696f53687274b5241874cd48beeb8c0db0071f3ea68ced527bdd2fc9cf33ddceeb434eeba8d0637a9af

test:
  secret_key_base: 748795ddcbaeda20bbffb214adc7841917c99efdec841b2768f51f3f6affbfc19e74cb7e23e647b8cce324539211c26938bd05972e38509c17d2529d814b65c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
